name: Pylint - Always Pass with Score Reporting

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pylint
    - name: Analysing the code with pylint
      id: pylint_run # Give this step an ID for later reference
      run: |
        pylint $(git ls-files '*.py') --output-format=text | tee pylint_output.txt || true
        # Explanation:
        #   --output-format=text:  Ensures consistent output for parsing.  VERY IMPORTANT.
        #   | tee pylint_output.txt:  Sends output to BOTH the console AND a file.
        #   || true:                 ALWAYS returns a success code (0).

    - name: Extract and Report Pylint Score
      if: always() # This ensures the summary is ALWAYS created
      run: |
        score=$(grep -oP 'Your code has been rated at \K[\d\.\-]+' pylint_output.txt)
        echo "Pylint Score: $score"
        # Set the score as an output variable (optional, but useful for other steps)
        echo "::set-output name=pylint_score::$score"

        # Create a summary (visible on the workflow run page)
        echo "## Pylint Report Summary" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY  # Add a blank line
        echo "Pylint Score:  **$score**" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "<details><summary>Click to see full Pylint output</summary>" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "```" >> $GITHUB_STEP_SUMMARY
        cat pylint_output.txt >> $GITHUB_STEP_SUMMARY
        echo "```" >> $GITHUB_STEP_SUMMARY
        echo "</details>" >> $GITHUB_STEP_SUMMARY